In [12]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from itertools import combinations
from rapidfuzz import fuzz

In [13]:
seed = 99
filepath_syn = Path(f"../data/synthetic/{seed}")
filepath_gt = Path(f"../data/ground_truth/{seed}")

customers_raw = pd.read_csv(filepath_syn/"customers_raw.csv")
products_raw = pd.read_csv(filepath_syn/"products_raw.csv")
orders_raw = pd.read_csv(filepath_syn/"orders_raw.csv")

customers_clean = pd.read_csv(filepath_gt/"customers_clean.csv")
products_clean = pd.read_csv(filepath_gt/"products_clean.csv")

In [14]:
def show_all(df, name=""):
    with pd.option_context("display.max_rows", None,
                           "display.max_columns", None,
                           "display.width", None):
        if name:
            print(f"=== {name}: {len(df)} rows ===")
        display(df)


def inspect_duplicates(df, subset=None, name=""):
    dups = df[df.duplicated(subset=subset, keep=False)]
    sort_cols = subset if subset else list(df.columns)
    with pd.option_context("display.max_rows", None,
                           "display.max_columns", None):
        print(f"=== {name}: {len(dups)} duplicate rows "
              f"(subset={subset or 'all columns'}) ===")
        display(dups.sort_values(by=sort_cols))

def inspect_fuzzy_duplicates(df, cols=None, exclude=None, threshold=85,
                             scorer=fuzz.ratio, name=""):
    exclude = set(exclude or [])
    if cols is None:                      
        cols = [c for c in df.columns if c not in exclude]
    sub = df[cols].fillna("").astype(str)
    recs = sub.to_dict("records")
    idx = df.index.tolist()

    rows = []
    for a, b in combinations(range(len(df)), 2):
        scores = {c: scorer(recs[a][c], recs[b][c]) for c in cols}
        avg = sum(scores.values()) / len(cols)
        if avg >= threshold:
            rows.append({"score": round(avg, 1), "idx_a": idx[a], "idx_b": idx[b],
                         **{f"{c}_a": recs[a][c] for c in cols},
                         **{f"{c}_b": recs[b][c] for c in cols}})

    result = (pd.DataFrame(rows).sort_values("score", ascending=False)
              .reset_index(drop=True))
    with pd.option_context("display.max_rows", None, "display.max_columns", None):
        print(f"=== {name}: {len(result)} fuzzy pairs "
              f"(threshold={threshold}, cols={cols}) ===")
        display(result)
    return result

In [18]:
# Customers

show_all(customers_raw.sort_values("customer_id"), "customers_raw")             #sorted raw
show_all(customers_clean.sort_values("customer_id"), "customers_clean")         #sorted clean
#show_all(customers_raw, "customers_raw")                                        #unsorted
#show_all(customers_clean, "customers_clean")                                    #unsorted

# Duplicates

#inspect_duplicates(customers_raw, name="customers_raw")
inspect_duplicates(customers_clean, name="customers_clean")    # 0 expected

inspect_fuzzy_duplicates(customers_raw, cols=["full_name", "email"], threshold=80, name="customers_raw");

=== customers_raw: 540 rows ===

,customer_id,full_name,email,country,registered_at
151,1,Hanife Gute-Scheuermann,hermann-josefhering@example.org,Niederlande,September 25 2020
281,2,Monika Kraus,scholzadelheid@example.org,Netherlands,1690934400
250,3,Robby Zirme B.Eng.,nstoll@example.org,France,1701648000
374,4,Prof. Gunther Carsten,moechlichenmaik@example.com,GB,2020-05-12
375,5,Kristiane Albers,xhaase@example.net,CH,1599523200
488,6,Karen Gumprich MBA.,klemtflorian@example.org,FRA,2021-05-14
104,7,Lilija Gierschner B.A.,doerschneranatolij@example.org,FR,January 11 2024
411,8,Frau Valeska Löffler,fechnerlorenzo@example.net,schweiz,2020-01-18
402,9,Genoveva Ernst-Preiß,ygute@example.org,AT,June 12 2025
131,10,Heinz-Willi Hertrampf MBA.,nikolaustaesche@example.com,Italy,2020-06-22
234,11,Paul-Heinz Trupp-Schinke,edithalange@example.org,Holland,2020-10-26
108,12,Claudio Hübel,hans-dieterlange@example.org,Polen,1633478400
228,13,Patricia Ortmann,milenahertrampf@example.org,Poland,January 28 2023
355,14,Univ.Prof. Arnd Otto,aldo90@example.com,OEsterreich,2021-11-03
277,15,Heiderose Kallert-Kuhl,xliebelt@example.net,England,14.10.2020
260,16,Herr Viktor Köhler,cwinkler@example.org,Belgium,August 25 2022
241,17,Univ.Prof. Osman Jockel B.Sc.,heinz-juergen36@example.com,France,September 23 2023
353,18,Thilo Mangold,ehertrampf@example.net,Netherlands,June 29 2022
194,19,Rebecca Müller,suzannehertrampf@example.com,United Kingdom,June 22 2022
133,20,Univ.Prof. Sabine Schmidt,karl-wernerkramer@example.net,GB,October 08 2025
513,21,Cosima Kramer B.Eng.,muratadolph@example.net,France,January 08 2023
192,22,Wiebke Gröttner,lisaschwital@example.com,Spanien,August 03 2025
361,23,Univ.Prof. Nina Trapp,ruedigerkaul@example.net,NL,1685145600
78,24,Birger Otto,abdullahpreiss@example.com,NaN,19.09.2025
209,25,Prof. Rene Martin,joseweiss@example.net,Schweiz,19.07.2023
17,26,Kristina Radisch B.Eng.,joanabaerer@example.org,Belgien,August 13 2022
296,27,Klaus Dieter Beckmann,lindaukrzysztof@example.com,Switzerland,2024-09-27
43,27,Klaus Dieter Beckmann,lindaukrzysztof@example.com,Switzerland,2024-09-27
306,28,Cornelia Wernecke,krokerrochus@example.org,England,2022-04-02
9,29,Galina Eckbauer B.A.,staesche@example.com,ES,1690070400
290,30,Ing. Fatih Hänel,vinko96@example.org,Austria,2024-01-28
83,31,Univ.Prof. Christa-Maria Bruder B.A.,apreiss@example.org,Polen,2022-10-21
159,32,Frau Gerhild Sölzer B.Sc.,evelin09@example.com,AUT,10.07.2023
404,32,Frau Gerhild Sölzer B.Sc.,evelin09@example.com,AUT,10.07.2023
408,33,Centa Ernst,kruschwitzarnd@example.org,Belgium,2022-11-29
127,34,Prof. Piotr Hornich B.A.,sbohlander@example.com,Spanien,December 14 2021
310,35,Boris Neureuther B.A.,karl-august51@example.net,Niederlande,1630972800
334,36,Univ.Prof. Hans D. Söding,weimerhalina@example.org,deutschland,January 25 2021
390,37,Conrad Ritter-Christoph,werneranica@example.net,ITA,24.03.2023
407,38,Ing. Sönke Zänker,elisabetschlosser@example.net,Poland,15.05.2021
370,39,Paula Bloch,mara63@example.com,DE,2021-07-11
20,40,Claus-Dieter Oestrovsky,heinrichpierre@example.net,Netherlands,28.10.2020
327,41,Prof. Helfried Wagner B.Sc.,paulinageisel@example.com,NaN,March 05 2023
535,42,Frauke Schacht,sauerrobert@example.org,ESP,1658534400
533,43,Dr. Wieslaw Atzler,marcella84@example.com,PL,19.01.2021
369,44,Dipl.-Ing. Ricarda Briemer B.Sc.,gottlob95@example.com,AT,2025-08-24
313,45,Rosa Beer,nhiller@example.org,Belgien,August 29 2024
24,46,Necati Steuer-Bähr,joana66@example.net,Polen,December 08 2021
343,47,Prof. Hansjürgen Bloch,immoseifert@example.com,FRA,24.05.2021
514,48,Heinz-Joachim Adolph,gutknechtfrancisco@example.org,UK,1746748800
510,49,Anna-Marie Hermighausen,claudiawieloch@example.com,Belgien,April 07 2021
217,50,Vlado Seifert,paffrathriza@example.com,GER,1597622400
94,51,Prof. Eric Karge,eeigenwillig@example.net,Spanien,09.10.2020
304,52,Joanna Freudenberger,jasminruppersberger@example.com,SUI,09.10.2021
164,53,Heinz-Josef Schmidtke,selmagerlach@example.org,FR,2024-01-17
74,54,Dr. Siegmar Striebitz B.Eng.,gabriellaplath@example.net,Switzerland,2024-04-16
381,55,Erik Hendriks,heidemarietlustek@example.com,Belgien,13.05.2023
484,56,Erol Hermann,kristiane95@example.com,Großbritannien,2021-08-10
441,57,Robert Schottin,bendersueleyman@example.org,CH,September 06 2022
382,58,Vincenzo Binner B.Eng.,juergensteckel@example.com,Poland,February 01 2020
244,59,Cristina van der Dussen,ercan25@example.com,NaN,1616025600
115,60,Katerina Heß,torbenbluemel@example.org,deutschland,07.01.2023
85,61,Dr. Leander Budig MBA.,klemtthekla@example.com,NaN,2023-03-11
39,62,Prof. Cosimo Zahn B.Sc.,baumhanns@example.org,Germany,21.11.2021
235,63,Ludwina Hertrampf,seidelabdul@example.com,NaN,December 20 2020
119,64,Frau Marta Vogt,aleksandra68@example.com,BE,October 03 2024
321,65,Gabriella Trub,manja14@example.net,NL,January 26 2022
372,66,Vittorio Beer,jovanjunk@example.net,AT,14.11.2020
464,66,Vittorio Beer,jovanjunk@example.net,AT,14.11.2020
197,67,Susan Jäntsch,heinimargraf@example.net,NL,October 13 2023
492,68,Kurt Weimer,curt61@example.net,Österreich,24.02.2020
360,69,Jeannine Wieloch,yloos@example.com,schweiz,2024-05-02
387,70,Prof. Necati Reinhardt B.Sc.,rocco31@example.net,Italien,19.05.2022
478,71,Natalie Niemeier B.Eng.,textoralois@example.org,UK,October 15 2024
37,72,Manfred Ehlert,bgroettner@example.net,Deutshcland,1754352000
106,73,Albin Eberhardt,heinz-josef31@example.org,NL,2023-08-28
213,74,Claudia Ernst,hans-d61@example.com,ES,2021-07-27
125,75,Dipl.-Ing. Magda Dietz,heusertuelay@example.net,CH,02.08.2022
212,76,Siglinde Vogt,katarzynahoefig@example.net,Polen,2021-01-19
33,77,Petros Schleich,hermannwilhelm@example.com,Niederlande,03.02.2021
84,78,Lilo Nette,milenawinkler@example.net,Frankreich,August 10 2022
181,79,Elisa Otto B.Eng.,valerijhoelzenbecher@example.org,Deutshcland,1628899200
287,80,Josephine Eckbauer,elfriedeklapp@example.net,FR,1716336000
322,81,Enver Röhricht,jzaenker@example.net,BE,January 02 2020
292,82,Mirjana Zimmer,ysalz@example.org,ITA,02.02.2020
117,83,Frau Hildegunde Mielcarek,carstenadelbert@example.org,Polen,30.09.2020
274,84,Ing. Drago Drewes B.A.,ina42@example.net,Niederlande,03.10.2025
110,85,Balthasar Schmiedt B.Sc.,andrei34@example.com,Schweiz,1667692800
525,86,Heinz-Willi Seip,wolf-dieter89@example.com,Spain,1636416000
363,87,Birgitta Beyer,herlinde83@example.org,BE,May 05 2025
96,88,Univ.Prof. Ivanka Fröhlich,brit28@example.net,Deutshcland,1660176000
261,88,Univ.Prof. Ivanka Fröhlich,brit28@example.net,Deutshcland,1660176000
122,89,Alan auch Schlauchin,gerhard26@example.org,schweiz,31.07.2020
418,90,Wally Steinberg,marta52@example.net,GB,1666051200
511,91,Ottmar Rogner,antonio56@example.org,Switzerland,29.05.2025
184,92,Herr Diethard Schottin,muelichenreinhold@example.com,Großbritannien,August 17 2024
27,93,Gundula Scheel-Segebahn,gheser@example.org,Holland,2022-12-28
396,94,Anto Hesse-Stiffel,adolphpatrik@example.com,OEsterreich,31.08.2022
386,95,Prof. Burkhardt Schleich B.Eng.,ryszard22@example.net,AT,February 06 2021
367,96,Yasemin Tintzmann,roggeanastasia@example.net,AT,1648166400
221,97,Fabian Langern-Pruschke,josephjaehn@example.com,Switzerland,07.04.2023
350,98,Severin Kaul,noackherbert@example.com,Italy,2025-07-16
283,99,Jakob Jacobi Jäckel,lianepatberg@example.org,Switzerland,2021-01-29
5,100,Rose-Marie Zorbach B.Sc.,camilla25@example.net,Schweiz,22.07.2024
152,101,Antonino Austermühle,isabellawaehner@example.org,Netherlands,2023-11-02
237,102,Mario Pruschke MBA.,tschuster@example.org,CH,04.11.2021
173,103,Laurenz Hartmann,filizlosekann@example.org,FR,January 25 2021
170,104,Evamaria Schlosser B.Sc.,jacobi-jaeckelbirger@example.net,Poland,1586563200
537,105,Prof. Hans-Peter Köhler MBA.,karstenruppersberger@example.com,ES,2025-12-07
318,106,Murat Beckmann-Zirme,christine58@example.org,Belgien,2025-09-01
490,107,Univ.Prof. Elsa Gierschner,woldemar16@example.net,FRA,2023-07-05
186,108,Wanda auch Schlauchin,wolf08@example.org,ITA,04.04.2020
0,109,Dörthe Gerlach,freudenbergerannemarie@example.org,Österreich,2022-07-20
345,110,Friedl Kreusel,rolf-dieter24@example.com,Spain,30.05.2021
436,111,Czeslaw Rogge,rmitschke@example.net,SUI,2024-02-04
389,112,Myriam Schüler,matthiasrosenow@example.org,OEsterreich,2025-11-16
58,113,Janko Kuhl,lottimosemann@example.org,PL,2024-04-02
425,114,Robert Stroh,xkabus@example.com,Italy,2024-07-10
68,115,Galina Hande,cichoriushelmar@example.net,deutschland,2022-02-07
505,116,Carolina Henschel-Trub,vhein@example.org,United Kingdom,2021-07-27
479,117,Otmar Blümel,schuchhardtwerner@example.com,GER,October 30 2021
450,118,Imelda Kambs,gnatzgalina@example.net,NaN,June 01 2025
236,119,Prof. Steffi Seifert,rjuncken@example.net,Frankreich,June 07 2021
339,120,Ilias Roskoth-Köster,valentinenette@example.com,Holland,12.12.2023
437,121,Dipl.-Ing. Mohammad Pohl,mschenk@example.com,Netherlands,1721606400
224,122,Lotti Mitschke B.Sc.,rbeer@example.com,Spanien,1629504000
307,123,Hagen Niemeier,kranzsoeren@example.com,Niederlande,2020-07-04
92,124,Carl Ziegert B.Sc.,wreuter@example.org,Netherlands,1608163200
269,125,Klaus-Ulrich Weinhage-Graf,valentinehartmann@example.com,Niederlande,03.03.2020
276,126,Melita Bonbach,wilmshans-willi@example.org,Spanien,1629504000
366,127,Prof. Edward Hamann B.Sc.,victorhettner@example.com,Poland,31.12.2022
140,128,Gesine Kallert,klaus-guenterbachmann@example.net,NaN,1699056000
506,129,Denis Salz,hamannludwina@example.com,SUI,May 27 2022
262,130,Gertraud Gotthard,pkaester@example.com,GER,2025-06-25
14,131,Univ.Prof. Jeannine Austermühle MBA.,hermighausenantonina@example.net,ES,October 07 2020
54,132,Babett Baum,xtrub@example.net,Niederlande,29.12.2025
16,133,Diethard Köhler,paolo95@example.net,Belgium,April 17 2022
118,134,Trude Weimer,reinhardt29@example.org,FRA,August 29 2025
487,135,Selma Renner,christophgordana@example.com,Italien,2020-08-11
351,136,Miodrag Gutknecht,kaulreiner@example.com,FR,17.11.2021
384,137,Herr Severin Eigenwillig B.Eng.,pgeisel@example.org,Italy,25.11.2022
232,138,Corina Kostolzin,alena22@example.net,OEsterreich,2024-12-04
289,139,Matthäus Bolander,antoniojaekel@example.com,ES,December 29 2023
340,139,Matthäus Bolander,antoniojaekel@example.com,ES,December 29 2023
53,140,Ansgar Etzler-Hövel,claire43@example.com,FR,12.01.2022
168,141,Falko Herrmann,mdowerg@example.org,FRA,1728086400
174,142,Herr Marcel Schäfer,malteniemeier@example.com,NL,2023-01-22
6,143,Leopold Wulf-Heintze,suzannelorch@example.net,ITA,November 10 2023
483,144,Hermine Gunpf,wheidrich@example.com,Belgien,1717027200
144,145,Oliver Harloff,wilhelmine73@example.org,AT,16.09.2024
264,146,Dieter Beckmann,joergenmaelzer@example.org,BE,2020-08-07
316,147,Denny Bachmann,diethardebert@example.org,NL,2020-08-01
123,148,Alberto Ullrich,lucie55@example.org,Italien,14.10.2023
489,149,Lina Biggen-Lorch,walfriedgunpf@example.net,AT,1702080000
201,150,Ulrike Buchholz,halil44@example.net,PL,2020-05-12
42,151,Micha Gute B.Sc.,karina39@example.com,NaN,09.12.2020
502,152,Sinaida Röhrdanz,nweinhage@example.org,Spanien,14.04.2020
15,153,Dipl.-Ing. Rolf-Peter Dussen van,hansgeorgehlert@example.org,BE,29.04.2025
101,154,Frau Lieschen Hettner,ziegertimmo@example.org,NaN,26.05.2024
286,155,Mike Schmiedt,mstiebitz@example.com,Switzerland,1744070400
461,156,Natalija Rust,anna-marie72@example.net,Italy,2023-12-14
50,157,Valeri Weller,pweitzel@example.net,Niederlande,March 03 2025
162,158,Theobald Ernst,segebahnchristof@example.org,Italien,2025-02-14
86,159,Prof. Calogero Pruschke MBA.,luisa04@example.com,NL,31.07.2021
255,160,Susann Scheuermann,boucseindorle@example.org,England,30.04.2024
79,161,Grazyna Eigenwillig,eugeniazahn@example.com,CH,2022-12-20
442,162,Waltraut Geisler B.Eng.,gundel33@example.net,Italy,1652486400
223,163,Doris Schmidt,wagenknechtmaike@example.com,NL,1765238400
314,164,Ibrahim Holsten-Seifert,valerij23@example.net,NaN,August 03 2022
120,165,Johannes Mies,alfonso50@example.com,United Kingdom,January 30 2021
438,166,Kristine Conradi,reinerwesack@example.net,Belgien,1731628800
477,167,Prof. Hans-Gerd Gude,marinabarth@example.net,France,15.11.2020
493,168,Frau Lissi Lübs B.Eng.,lwulf@example.net,NL,1708387200
520,169,Leonardo Carsten,lsager@example.net,ESP,February 19 2023
114,170,Ing. Gotthard Dobes B.Sc.,zobelgottfried@example.net,France,1643328000
485,171,Tamara Rose,luciehein@example.net,ESP,22.01.2024
245,172,Gernot Harloff,dstaude@example.com,GER,2020-06-26
29,173,Dr. Klaus-Werner Christoph,kranzhans-erich@example.net,Spain,19.09.2023
242,174,Eggert Roskoth-Loos,marcella11@example.org,Italien,2022-10-26
458,175,Dr. Dörthe Pärtzelt B.Sc.,kuhlistvan@example.net,France,2022-06-27
297,176,Dr. Solveig Römer B.Eng.,mschacht@example.com,Schweiz,14.06.2021
57,177,Brigitta Weimer B.A.,ryszardmitschke@example.com,IT,23.02.2022
189,178,Martine Kramer,constantin98@example.org,NaN,26.10.2021
178,179,Prof. Marina Reinhardt B.Sc.,bstiebitz@example.net,Frankreich,1593129600
471,180,Volkmar Davids MBA.,bnaser@example.org,Niederlande,November 30 2021
7,181,Falko Reichmann,igeissler@example.net,ESP,2021-11-28
80,182,Hannchen Seip,herta19@example.net,Holland,May 21 2025
40,183,Frau Norma Gumprich MBA.,iweinhold@example.org,Deutschland,1662422400
346,184,Cosima Hiller,evangelos37@example.com,AUT,29.11.2023
18,185,Luka Zirme,rzimmer@example.net,Polen,May 03 2021
128,186,Arndt Säuberlich,preissserpil@example.net,Poland,2022-09-13
415,187,Irmhild Beier,mudehans-gerhard@example.org,Frankreich,2022-06-13
180,188,Galina Beier-Gröttner,chantal79@example.net,Deutshcland,08.01.2025
202,189,Alwine Gutknecht-Scheuermann,ortmannannett@example.org,Poland,November 04 2021
198,190,Univ.Prof. Reinhardt Mülichen,erik78@example.org,Italy,November 04 2023
497,191,Angelo Weitzel-Rädel,renehein@example.org,NaN,28.02.2022
481,192,Marek Fechner-Bärer,karl-heinz57@example.org,PL,02.04.2023
38,193,Käthi Jessel B.Sc.,uschweitzer@example.org,Belgium,1758672000
365,194,Dorothea Seidel,marcelatzler@example.org,France,November 11 2025
446,195,Heinz-Gerd Peukert-Anders,anne-katrin66@example.net,Italien,1677456000
368,196,Univ.Prof. Antonios Kaul B.A.,klothildedoerr@example.org,Niederlande,22.08.2024
206,197,Heidrun Beier,heiderose44@example.org,Belgien,August 30 2020
205,198,Univ.Prof. Andrey Hörle B.Sc.,schmiedeckenora@example.com,PL,June 08 2024
158,199,Gerard Pärtzelt,misicherhellmut@example.org,PL,26.02.2021
419,200,Marlen Dobes,wilhelmine84@example.com,England,09.08.2020
171,201,Theodor Schacht MBA.,mohammedsegebahn@example.net,NaN,August 11 2024
499,202,Sybille Wirth,hschuchhardt@example.net,Italy,February 14 2020
515,203,Prof. Alois Börner,moritzpergande@example.com,France,20.06.2024
147,203,Prof. Alois Börner,moritzpergande@example.com,France,20.06.2024
504,204,Till Schacht MBA.,mgierschner@example.com,NaN,2025-02-19
222,205,Francesca Zirme,aeberhardt@example.net,AUT,1590537600
31,206,Heide Herrmann,kunibertjaehn@example.net,Italy,08.10.2020
138,207,Klaus Peter Birnbaum-Boucsein,lucia95@example.net,AT,1630195200
430,208,Dr. Nuri Losekann,hassanbiggen@example.net,England,May 23 2020
413,209,Gotthilf Becker,qmeister@example.net,Germany,February 26 2023
517,210,Juergen Hauffer MBA.,jolanthesalz@example.com,DE,1756944000
501,211,Herr Gunnar Bloch B.Sc.,brudereileen@example.net,Netherlands,25.02.2025
48,212,Valentin Spieß,ognatz@example.net,ITA,21.10.2024
338,213,Salvatore Scheibe,nicolausmargraf@example.net,Spanien,June 20 2023
124,214,Fernando Kusch-Gutknecht,yjaentsch@example.com,Poland,2022-03-21
89,215,Jasmin Zirme,janinneuschaefer@example.net,NaN,1749686400
229,216,Hans-Gerhard Hande-Sager,qspiess@example.com,GB,June 09 2024
97,217,Fatma Jäkel,hansjoerg42@example.com,Italien,2020-10-27
530,218,Anika Hübel,lsteinberg@example.org,NaN,October 26 2023
331,219,Hans-Wilhelm Gierschner,ddietz@example.net,OEsterreich,2023-12-02
45,220,Herr Alex Rörricht MBA.,apostolosdoering@example.org,Holland,1662595200
294,221,Prof. Dörthe Scheel B.Eng.,heide-marieheser@example.net,Holland,27.10.2022
166,222,Berta Dietz-Dussen van,ngerlach@example.net,SUI,August 20 2021
156,223,Claus Röhrdanz,ingridkaul@example.org,ITA,2022-07-08
185,224,Herr Hans-Dietrich Kambs,erdogan13@example.net,Belgien,05.02.2023
293,225,Helga Schomber,markushoevel@example.com,NaN,1650153600
473,226,Kazim Kusch,kaesterelke@example.org,Switzerland,30.03.2024
357,227,Senol Klapp,hans-friedrichloewer@example.com,CH,December 18 2022
416,228,Hans-Walter Gorlitz,ymuehle@example.com,BE,01.11.2023
215,229,Dr. Liesbeth Nette,erkan19@example.net,Netherlands,25.04.2021
282,230,Ing. Christa-Maria Martin MBA.,austermuehledina@example.com,Niederlande,2020-05-07
204,231,Antonios Sager,birnbaumsimon@example.com,PL,2022-08-19
303,232,Margot Kraus,rennerevamaria@example.org,Switzerland,1695859200
63,233,Heinz Dieter Mentzel,maryeigenwillig@example.net,ES,2020-07-05
183,234,Frau Susana Heß B.Sc.,biggenrichard@example.org,IT,1586390400
71,235,Lena Bolzmann-Junitz,hellahecker@example.net,France,January 10 2023
528,236,Steffi Schaaf,plathjens-peter@example.net,ITA,1582329600
468,237,Gundolf Staude,orhanschuster@example.net,Belgien,1763078400
200,237,Gundolf Staude,orhanschuster@example.net,Belgien,1763078400
66,238,Hellmuth Mülichen,urbandietz@example.org,England,2020-06-16
284,239,Elzbieta Geisler-Weinhage,wulfrosl@example.com,Niederlande,2023-05-02
417,240,Petros Keudel B.Eng.,geislerlambert@example.org,SUI,1730851200
440,241,Rabea Bohlander-Bohlander,radischelvira@example.com,BE,May 29 2025
395,242,Vinzenz Benthin,philipjacobi-jaeckel@example.com,England,22.06.2021
163,243,Annegrete Ditschlerin,hellasontag@example.com,Belgium,April 30 2022
67,244,Mirko Rogner B.A.,zbigniew80@example.org,Switzerland,October 02 2024
253,245,Harry Jähn-Trapp,andrew68@example.net,Austria,2021-06-19
240,246,Heide-Marie Krebs-Graf,eimerklaus-michael@example.com,Polen,2024-06-26
191,247,Prof. Lea Striebitz,henkniklas@example.com,Frankreich,2020-01-19
169,248,Frithjof Heidrich,dorotakreusel@example.net,BE,10.03.2025
465,249,Prof. Theodora Lindner B.Sc.,hartmuth01@example.net,Poland,20.07.2021
383,250,Janusz Junck,junckserpil@example.net,Deutschland,October 02 2021
59,251,Helma Grein Groth,dhande@example.net,Austria,23.07.2021
376,252,Frau Violetta Tröst,zdravkokensy@example.org,ES,18.06.2025
142,253,Ing. Joana Lindau,heikeflantz@example.org,Belgium,1583884800
72,254,Jaqueline Steuer,dusan93@example.net,AUT,2022-03-26
179,255,Karl Heinz Vogt,robinhentschel@example.net,Spain,September 13 2020
199,256,Siegrun Gute MBA.,emilhein@example.net,Deutschland,24.07.2024
412,257,Veronica Bohnbach MBA.,carminekoehler@example.com,Großbritannien,1699920000
457,258,Aziz Geißler,marko07@example.com,Polen,1669593600
522,259,Univ.Prof. Miroslaw Lindau B.A.,ylindner@example.org,NaN,May 05 2022
431,260,Celal Briemer,wagnergretchen@example.net,Germany,2021-03-13
105,261,Mechtild Juncken,nermin05@example.org,United Kingdom,23.04.2021
508,262,Dr. Adrian Berger B.Eng.,qschinke@example.com,ESP,26.05.2021
456,263,Univ.Prof. Rosalinde Möchlichen,lambertthanel@example.net,NaN,2025-08-16
319,264,Ortrun Briemer,dippelheino@example.com,IT,2023-10-18
521,265,Albina Segebahn,bkraushaar@example.com,Switzerland,1678147200
428,266,Rainer Lorch,qhaering@example.com,CH,26.10.2022
434,267,Dogan Jessel,elma66@example.org,UK,1631145600
324,268,Univ.Prof. Jane Bolnbach,soenke72@example.net,NaN,16.12.2022
500,269,Isa Gotthard,fischerantonios@example.net,Holland,27.10.2024
285,270,Selma Henck,zdoerschner@example.com,Deutshcland,1597276800
252,271,Elsa Börner,hesserosel@example.org,DE,April 13 2022
410,272,Ira Drubin,nsalz@example.com,ESP,2021-10-22
405,273,Kerstin Atzler-Eigenwillig,kensyadeline@example.org,NaN,2020-12-08
337,274,Herr Ilias Anders B.A.,franca81@example.org,NaN,2020-10-27
453,275,Freia Röhricht,romanatroest@example.org,Poland,July 08 2022
432,276,Univ.Prof. Knud Dietz,tomislav90@example.org,IT,1712534400
301,277,Rolf-Dieter Putz,davidklingelhoefer@example.net,NaN,18.05.2020
132,278,Herr Hasso Baum B.Sc.,lili60@example.com,Belgien,17.09.2020

=== customers_clean: 500 rows ===

,customer_id,full_name,email,country_code,registered_at
0,1,Hanife Gute-Scheuermann,hermann-josefhering@example.org,NL,2020-09-25
1,2,Monika Kraus,scholzadelheid@example.org,NL,2023-08-02
2,3,Robby Zirme B.Eng.,nstoll@example.org,FR,2023-12-04
3,4,Prof. Gunther Carsten,moechlichenmaik@example.com,GB,2020-05-12
4,5,Kristiane Albers,xhaase@example.net,CH,2020-09-08
5,6,Karen Gumprich MBA.,klemtflorian@example.org,FR,2021-05-14
6,7,Lilija Gierschner B.A.,doerschneranatolij@example.org,FR,2024-01-11
7,8,Frau Valeska Löffler,fechnerlorenzo@example.net,CH,2020-01-18
8,9,Genoveva Ernst-Preiß,ygute@example.org,AT,2025-06-12
9,10,Heinz-Willi Hertrampf MBA.,nikolaustaesche@example.com,IT,2020-06-22
10,11,Paul-Heinz Trupp-Schinke,edithalange@example.org,NL,2020-10-26
11,12,Claudio Hübel,hans-dieterlange@example.org,PL,2021-10-06
12,13,Patricia Ortmann,milenahertrampf@example.org,PL,2023-01-28
13,14,Univ.Prof. Arnd Otto,aldo90@example.com,AT,2021-11-03
14,15,Heiderose Kallert-Kuhl,xliebelt@example.net,GB,2020-10-14
15,16,Herr Viktor Köhler,cwinkler@example.org,BE,2022-08-25
16,17,Univ.Prof. Osman Jockel B.Sc.,heinz-juergen36@example.com,FR,2023-09-23
17,18,Thilo Mangold,ehertrampf@example.net,NL,2022-06-29
18,19,Rebecca Müller,suzannehertrampf@example.com,GB,2022-06-22
19,20,Univ.Prof. Sabine Schmidt,karl-wernerkramer@example.net,GB,2025-10-08
20,21,Cosima Kramer B.Eng.,muratadolph@example.net,FR,2023-01-08
21,22,Wiebke Gröttner,lisaschwital@example.com,ES,2025-08-03
22,23,Univ.Prof. Nina Trapp,ruedigerkaul@example.net,NL,2023-05-27
23,24,Birger Otto,abdullahpreiss@example.com,FR,2025-09-19
24,25,Prof. Rene Martin,joseweiss@example.net,CH,2023-07-19
25,26,Kristina Radisch B.Eng.,joanabaerer@example.org,BE,2022-08-13
26,27,Klaus Dieter Beckmann,lindaukrzysztof@example.com,CH,2024-09-27
27,28,Cornelia Wernecke,krokerrochus@example.org,GB,2022-04-02
28,29,Galina Eckbauer B.A.,staesche@example.com,ES,2023-07-23
29,30,Ing. Fatih Hänel,vinko96@example.org,AT,2024-01-28
30,31,Univ.Prof. Christa-Maria Bruder B.A.,apreiss@example.org,PL,2022-10-21
31,32,Frau Gerhild Sölzer B.Sc.,evelin09@example.com,AT,2023-07-10
32,33,Centa Ernst,kruschwitzarnd@example.org,BE,2022-11-29
33,34,Prof. Piotr Hornich B.A.,sbohlander@example.com,ES,2021-12-14
34,35,Boris Neureuther B.A.,karl-august51@example.net,NL,2021-09-07
35,36,Univ.Prof. Hans D. Söding,weimerhalina@example.org,DE,2021-01-25
36,37,Conrad Ritter-Christoph,werneranica@example.net,IT,2023-03-24
37,38,Ing. Sönke Zänker,elisabetschlosser@example.net,PL,2021-05-15
38,39,Paula Bloch,mara63@example.com,DE,2021-07-11
39,40,Claus-Dieter Oestrovsky,heinrichpierre@example.net,NL,2020-10-28
40,41,Prof. Helfried Wagner B.Sc.,paulinageisel@example.com,FR,2023-03-05
41,42,Frauke Schacht,sauerrobert@example.org,ES,2022-07-23
42,43,Dr. Wieslaw Atzler,marcella84@example.com,PL,2021-01-19
43,44,Dipl.-Ing. Ricarda Briemer B.Sc.,gottlob95@example.com,AT,2025-08-24
44,45,Rosa Beer,nhiller@example.org,BE,2024-08-29
45,46,Necati Steuer-Bähr,joana66@example.net,PL,2021-12-08
46,47,Prof. Hansjürgen Bloch,immoseifert@example.com,FR,2021-05-24
47,48,Heinz-Joachim Adolph,gutknechtfrancisco@example.org,GB,2025-05-09
48,49,Anna-Marie Hermighausen,claudiawieloch@example.com,BE,2021-04-07
49,50,Vlado Seifert,paffrathriza@example.com,DE,2020-08-17
50,51,Prof. Eric Karge,eeigenwillig@example.net,ES,2020-10-09
51,52,Joanna Freudenberger,jasminruppersberger@example.com,CH,2021-10-09
52,53,Heinz-Josef Schmidtke,selmagerlach@example.org,FR,2024-01-17
53,54,Dr. Siegmar Striebitz B.Eng.,gabriellaplath@example.net,CH,2024-04-16
54,55,Erik Hendriks,heidemarietlustek@example.com,BE,2023-05-13
55,56,Erol Hermann,kristiane95@example.com,GB,2021-08-10
56,57,Robert Schottin,bendersueleyman@example.org,CH,2022-09-06
57,58,Vincenzo Binner B.Eng.,juergensteckel@example.com,PL,2020-02-01
58,59,Cristina van der Dussen,ercan25@example.com,CH,2021-03-18
59,60,Katerina Heß,torbenbluemel@example.org,DE,2023-01-07
60,61,Dr. Leander Budig MBA.,klemtthekla@example.com,AT,2023-03-11
61,62,Prof. Cosimo Zahn B.Sc.,baumhanns@example.org,DE,2021-11-21
62,63,Ludwina Hertrampf,seidelabdul@example.com,CH,2020-12-20
63,64,Frau Marta Vogt,aleksandra68@example.com,BE,2024-10-03
64,65,Gabriella Trub,manja14@example.net,NL,2022-01-26
65,66,Vittorio Beer,jovanjunk@example.net,AT,2020-11-14
66,67,Susan Jäntsch,heinimargraf@example.net,NL,2023-10-13
67,68,Kurt Weimer,curt61@example.net,AT,2020-02-24
68,69,Jeannine Wieloch,yloos@example.com,CH,2024-05-02
69,70,Prof. Necati Reinhardt B.Sc.,rocco31@example.net,IT,2022-05-19
70,71,Natalie Niemeier B.Eng.,textoralois@example.org,GB,2024-10-15
71,72,Manfred Ehlert,bgroettner@example.net,DE,2025-08-05
72,73,Albin Eberhardt,heinz-josef31@example.org,NL,2023-08-28
73,74,Claudia Ernst,hans-d61@example.com,ES,2021-07-27
74,75,Dipl.-Ing. Magda Dietz,heusertuelay@example.net,CH,2022-08-02
75,76,Siglinde Vogt,katarzynahoefig@example.net,PL,2021-01-19
76,77,Petros Schleich,hermannwilhelm@example.com,NL,2021-02-03
77,78,Lilo Nette,milenawinkler@example.net,FR,2022-08-10
78,79,Elisa Otto B.Eng.,valerijhoelzenbecher@example.org,DE,2021-08-14
79,80,Josephine Eckbauer,elfriedeklapp@example.net,FR,2024-05-22
80,81,Enver Röhricht,jzaenker@example.net,BE,2020-01-02
81,82,Mirjana Zimmer,ysalz@example.org,IT,2020-02-02
82,83,Frau Hildegunde Mielcarek,carstenadelbert@example.org,PL,2020-09-30
83,84,Ing. Drago Drewes B.A.,ina42@example.net,NL,2025-10-03
84,85,Balthasar Schmiedt B.Sc.,andrei34@example.com,CH,2022-11-06
85,86,Heinz-Willi Seip,wolf-dieter89@example.com,ES,2021-11-09
86,87,Birgitta Beyer,herlinde83@example.org,BE,2025-05-05
87,88,Univ.Prof. Ivanka Fröhlich,brit28@example.net,DE,2022-08-11
88,89,Alan auch Schlauchin,gerhard26@example.org,CH,2020-07-31
89,90,Wally Steinberg,marta52@example.net,GB,2022-10-18
90,91,Ottmar Rogner,antonio56@example.org,CH,2025-05-29
91,92,Herr Diethard Schottin,muelichenreinhold@example.com,GB,2024-08-17
92,93,Gundula Scheel-Segebahn,gheser@example.org,NL,2022-12-28
93,94,Anto Hesse-Stiffel,adolphpatrik@example.com,AT,2022-08-31
94,95,Prof. Burkhardt Schleich B.Eng.,ryszard22@example.net,AT,2021-02-06
95,96,Yasemin Tintzmann,roggeanastasia@example.net,AT,2022-03-25
96,97,Fabian Langern-Pruschke,josephjaehn@example.com,CH,2023-04-07
97,98,Severin Kaul,noackherbert@example.com,IT,2025-07-16
98,99,Jakob Jacobi Jäckel,lianepatberg@example.org,CH,2021-01-29
99,100,Rose-Marie Zorbach B.Sc.,camilla25@example.net,CH,2024-07-22
100,101,Antonino Austermühle,isabellawaehner@example.org,NL,2023-11-02
101,102,Mario Pruschke MBA.,tschuster@example.org,CH,2021-11-04
102,103,Laurenz Hartmann,filizlosekann@example.org,FR,2021-01-25
103,104,Evamaria Schlosser B.Sc.,jacobi-jaeckelbirger@example.net,PL,2020-04-11
104,105,Prof. Hans-Peter Köhler MBA.,karstenruppersberger@example.com,ES,2025-12-07
105,106,Murat Beckmann-Zirme,christine58@example.org,BE,2025-09-01
106,107,Univ.Prof. Elsa Gierschner,woldemar16@example.net,FR,2023-07-05
107,108,Wanda auch Schlauchin,wolf08@example.org,IT,2020-04-04
108,109,Dörthe Gerlach,freudenbergerannemarie@example.org,AT,2022-07-20
109,110,Friedl Kreusel,rolf-dieter24@example.com,ES,2021-05-30
110,111,Czeslaw Rogge,rmitschke@example.net,CH,2024-02-04
111,112,Myriam Schüler,matthiasrosenow@example.org,AT,2025-11-16
112,113,Janko Kuhl,lottimosemann@example.org,PL,2024-04-02
113,114,Robert Stroh,xkabus@example.com,IT,2024-07-10
114,115,Galina Hande,cichoriushelmar@example.net,DE,2022-02-07
115,116,Carolina Henschel-Trub,vhein@example.org,GB,2021-07-27
116,117,Otmar Blümel,schuchhardtwerner@example.com,DE,2021-10-30
117,118,Imelda Kambs,gnatzgalina@example.net,ES,2025-06-01
118,119,Prof. Steffi Seifert,rjuncken@example.net,FR,2021-06-07
119,120,Ilias Roskoth-Köster,valentinenette@example.com,NL,2023-12-12
120,121,Dipl.-Ing. Mohammad Pohl,mschenk@example.com,NL,2024-07-22
121,122,Lotti Mitschke B.Sc.,rbeer@example.com,ES,2021-08-21
122,123,Hagen Niemeier,kranzsoeren@example.com,NL,2020-07-04
123,124,Carl Ziegert B.Sc.,wreuter@example.org,NL,2020-12-17
124,125,Klaus-Ulrich Weinhage-Graf,valentinehartmann@example.com,NL,2020-03-03
125,126,Melita Bonbach,wilmshans-willi@example.org,ES,2021-08-21
126,127,Prof. Edward Hamann B.Sc.,victorhettner@example.com,PL,2022-12-31
127,128,Gesine Kallert,klaus-guenterbachmann@example.net,AT,2023-11-04
128,129,Denis Salz,hamannludwina@example.com,CH,2022-05-27
129,130,Gertraud Gotthard,pkaester@example.com,DE,2025-06-25
130,131,Univ.Prof. Jeannine Austermühle MBA.,hermighausenantonina@example.net,ES,2020-10-07
131,132,Babett Baum,xtrub@example.net,NL,2025-12-29
132,133,Diethard Köhler,paolo95@example.net,BE,2022-04-17
133,134,Trude Weimer,reinhardt29@example.org,FR,2025-08-29
134,135,Selma Renner,christophgordana@example.com,IT,2020-08-11
135,136,Miodrag Gutknecht,kaulreiner@example.com,FR,2021-11-17
136,137,Herr Severin Eigenwillig B.Eng.,pgeisel@example.org,IT,2022-11-25
137,138,Corina Kostolzin,alena22@example.net,AT,2024-12-04
138,139,Matthäus Bolander,antoniojaekel@example.com,ES,2023-12-29
139,140,Ansgar Etzler-Hövel,claire43@example.com,FR,2022-01-12
140,141,Falko Herrmann,mdowerg@example.org,FR,2024-10-05
141,142,Herr Marcel Schäfer,malteniemeier@example.com,NL,2023-01-22
142,143,Leopold Wulf-Heintze,suzannelorch@example.net,IT,2023-11-10
143,144,Hermine Gunpf,wheidrich@example.com,BE,2024-05-30
144,145,Oliver Harloff,wilhelmine73@example.org,AT,2024-09-16
145,146,Dieter Beckmann,joergenmaelzer@example.org,BE,2020-08-07
146,147,Denny Bachmann,diethardebert@example.org,NL,2020-08-01
147,148,Alberto Ullrich,lucie55@example.org,IT,2023-10-14
148,149,Lina Biggen-Lorch,walfriedgunpf@example.net,AT,2023-12-09
149,150,Ulrike Buchholz,halil44@example.net,PL,2020-05-12
150,151,Micha Gute B.Sc.,karina39@example.com,IT,2020-12-09
151,152,Sinaida Röhrdanz,nweinhage@example.org,ES,2020-04-14
152,153,Dipl.-Ing. Rolf-Peter Dussen van,hansgeorgehlert@example.org,BE,2025-04-29
153,154,Frau Lieschen Hettner,ziegertimmo@example.org,PL,2024-05-26
154,155,Mike Schmiedt,mstiebitz@example.com,CH,2025-04-08
155,156,Natalija Rust,anna-marie72@example.net,IT,2023-12-14
156,157,Valeri Weller,pweitzel@example.net,NL,2025-03-03
157,158,Theobald Ernst,segebahnchristof@example.org,IT,2025-02-14
158,159,Prof. Calogero Pruschke MBA.,luisa04@example.com,NL,2021-07-31
159,160,Susann Scheuermann,boucseindorle@example.org,GB,2024-04-30
160,161,Grazyna Eigenwillig,eugeniazahn@example.com,CH,2022-12-20
161,162,Waltraut Geisler B.Eng.,gundel33@example.net,IT,2022-05-14
162,163,Doris Schmidt,wagenknechtmaike@example.com,NL,2025-12-09
163,164,Ibrahim Holsten-Seifert,valerij23@example.net,GB,2022-08-03
164,165,Johannes Mies,alfonso50@example.com,GB,2021-01-30
165,166,Kristine Conradi,reinerwesack@example.net,BE,2024-11-15
166,167,Prof. Hans-Gerd Gude,marinabarth@example.net,FR,2020-11-15
167,168,Frau Lissi Lübs B.Eng.,lwulf@example.net,NL,2024-02-20
168,169,Leonardo Carsten,lsager@example.net,ES,2023-02-19
169,170,Ing. Gotthard Dobes B.Sc.,zobelgottfried@example.net,FR,2022-01-28
170,171,Tamara Rose,luciehein@example.net,ES,2024-01-22
171,172,Gernot Harloff,dstaude@example.com,DE,2020-06-26
172,173,Dr. Klaus-Werner Christoph,kranzhans-erich@example.net,ES,2023-09-19
173,174,Eggert Roskoth-Loos,marcella11@example.org,IT,2022-10-26
174,175,Dr. Dörthe Pärtzelt B.Sc.,kuhlistvan@example.net,FR,2022-06-27
175,176,Dr. Solveig Römer B.Eng.,mschacht@example.com,CH,2021-06-14
176,177,Brigitta Weimer B.A.,ryszardmitschke@example.com,IT,2022-02-23
177,178,Martine Kramer,constantin98@example.org,NL,2021-10-26
178,179,Prof. Marina Reinhardt B.Sc.,bstiebitz@example.net,FR,2020-06-26
179,180,Volkmar Davids MBA.,bnaser@example.org,NL,2021-11-30
180,181,Falko Reichmann,igeissler@example.net,ES,2021-11-28
181,182,Hannchen Seip,herta19@example.net,NL,2025-05-21
182,183,Frau Norma Gumprich MBA.,iweinhold@example.org,DE,2022-09-06
183,184,Cosima Hiller,evangelos37@example.com,AT,2023-11-29
184,185,Luka Zirme,rzimmer@example.net,PL,2021-05-03
185,186,Arndt Säuberlich,preissserpil@example.net,PL,2022-09-13
186,187,Irmhild Beier,mudehans-gerhard@example.org,FR,2022-06-13
187,188,Galina Beier-Gröttner,chantal79@example.net,DE,2025-01-08
188,189,Alwine Gutknecht-Scheuermann,ortmannannett@example.org,PL,2021-11-04
189,190,Univ.Prof. Reinhardt Mülichen,erik78@example.org,IT,2023-11-04
190,191,Angelo Weitzel-Rädel,renehein@example.org,CH,2022-02-28
191,192,Marek Fechner-Bärer,karl-heinz57@example.org,PL,2023-04-02
192,193,Käthi Jessel B.Sc.,uschweitzer@example.org,BE,2025-09-24
193,194,Dorothea Seidel,marcelatzler@example.org,FR,2025-11-11
194,195,Heinz-Gerd Peukert-Anders,anne-katrin66@example.net,IT,2023-02-27
195,196,Univ.Prof. Antonios Kaul B.A.,klothildedoerr@example.org,NL,2024-08-22
196,197,Heidrun Beier,heiderose44@example.org,BE,2020-08-30
197,198,Univ.Prof. Andrey Hörle B.Sc.,schmiedeckenora@example.com,PL,2024-06-08
198,199,Gerard Pärtzelt,misicherhellmut@example.org,PL,2021-02-26
199,200,Marlen Dobes,wilhelmine84@example.com,GB,2020-08-09
200,201,Theodor Schacht MBA.,mohammedsegebahn@example.net,GB,2024-08-11
201,202,Sybille Wirth,hschuchhardt@example.net,IT,2020-02-14
202,203,Prof. Alois Börner,moritzpergande@example.com,FR,2024-06-20
203,204,Till Schacht MBA.,mgierschner@example.com,DE,2025-02-19
204,205,Francesca Zirme,aeberhardt@example.net,AT,2020-05-27
205,206,Heide Herrmann,kunibertjaehn@example.net,IT,2020-10-08
206,207,Klaus Peter Birnbaum-Boucsein,lucia95@example.net,AT,2021-08-29
207,208,Dr. Nuri Losekann,hassanbiggen@example.net,GB,2020-05-23
208,209,Gotthilf Becker,qmeister@example.net,DE,2023-02-26
209,210,Juergen Hauffer MBA.,jolanthesalz@example.com,DE,2025-09-04
210,211,Herr Gunnar Bloch B.Sc.,brudereileen@example.net,NL,2025-02-25
211,212,Valentin Spieß,ognatz@example.net,IT,2024-10-21
212,213,Salvatore Scheibe,nicolausmargraf@example.net,ES,2023-06-20
213,214,Fernando Kusch-Gutknecht,yjaentsch@example.com,PL,2022-03-21
214,215,Jasmin Zirme,janinneuschaefer@example.net,GB,2025-06-12
215,216,Hans-Gerhard Hande-Sager,qspiess@example.com,GB,2024-06-09
216,217,Fatma Jäkel,hansjoerg42@example.com,IT,2020-10-27
217,218,Anika Hübel,lsteinberg@example.org,FR,2023-10-26
218,219,Hans-Wilhelm Gierschner,ddietz@example.net,AT,2023-12-02
219,220,Herr Alex Rörricht MBA.,apostolosdoering@example.org,NL,2022-09-08
220,221,Prof. Dörthe Scheel B.Eng.,heide-marieheser@example.net,NL,2022-10-27
221,222,Berta Dietz-Dussen van,ngerlach@example.net,CH,2021-08-20
222,223,Claus Röhrdanz,ingridkaul@example.org,IT,2022-07-08
223,224,Herr Hans-Dietrich Kambs,erdogan13@example.net,BE,2023-02-05
224,225,Helga Schomber,markushoevel@example.com,ES,2022-04-17
225,226,Kazim Kusch,kaesterelke@example.org,CH,2024-03-30
226,227,Senol Klapp,hans-friedrichloewer@example.com,CH,2022-12-18
227,228,Hans-Walter Gorlitz,ymuehle@example.com,BE,2023-11-01
228,229,Dr. Liesbeth Nette,erkan19@example.net,NL,2021-04-25
229,230,Ing. Christa-Maria Martin MBA.,austermuehledina@example.com,NL,2020-05-07
230,231,Antonios Sager,birnbaumsimon@example.com,PL,2022-08-19
231,232,Margot Kraus,rennerevamaria@example.org,CH,2023-09-28
232,233,Heinz Dieter Mentzel,maryeigenwillig@example.net,ES,2020-07-05
233,234,Frau Susana Heß B.Sc.,biggenrichard@example.org,IT,2020-04-09
234,235,Lena Bolzmann-Junitz,hellahecker@example.net,FR,2023-01-10
235,236,Steffi Schaaf,plathjens-peter@example.net,IT,2020-02-22
236,237,Gundolf Staude,orhanschuster@example.net,BE,2025-11-14
237,238,Hellmuth Mülichen,urbandietz@example.org,GB,2020-06-16
238,239,Elzbieta Geisler-Weinhage,wulfrosl@example.com,NL,2023-05-02
239,240,Petros Keudel B.Eng.,geislerlambert@example.org,CH,2024-11-06
240,241,Rabea Bohlander-Bohlander,radischelvira@example.com,BE,2025-05-29
241,242,Vinzenz Benthin,philipjacobi-jaeckel@example.com,GB,2021-06-22
242,243,Annegrete Ditschlerin,hellasontag@example.com,BE,2022-04-30
243,244,Mirko Rogner B.A.,zbigniew80@example.org,CH,2024-10-02
244,245,Harry Jähn-Trapp,andrew68@example.net,AT,2021-06-19
245,246,Heide-Marie Krebs-Graf,eimerklaus-michael@example.com,PL,2024-06-26
246,247,Prof. Lea Striebitz,henkniklas@example.com,FR,2020-01-19
247,248,Frithjof Heidrich,dorotakreusel@example.net,BE,2025-03-10
248,249,Prof. Theodora Lindner B.Sc.,hartmuth01@example.net,PL,2021-07-20
249,250,Janusz Junck,junckserpil@example.net,DE,2021-10-02
250,251,Helma Grein Groth,dhande@example.net,AT,2021-07-23
251,252,Frau Violetta Tröst,zdravkokensy@example.org,ES,2025-06-18
252,253,Ing. Joana Lindau,heikeflantz@example.org,BE,2020-03-11
253,254,Jaqueline Steuer,dusan93@example.net,AT,2022-03-26
254,255,Karl Heinz Vogt,robinhentschel@example.net,ES,2020-09-13
255,256,Siegrun Gute MBA.,emilhein@example.net,DE,2024-07-24
256,257,Veronica Bohnbach MBA.,carminekoehler@example.com,GB,2023-11-14
257,258,Aziz Geißler,marko07@example.com,PL,2022-11-28
258,259,Univ.Prof. Miroslaw Lindau B.A.,ylindner@example.org,IT,2022-05-05
259,260,Celal Briemer,wagnergretchen@example.net,DE,2021-03-13
260,261,Mechtild Juncken,nermin05@example.org,GB,2021-04-23
261,262,Dr. Adrian Berger B.Eng.,qschinke@example.com,ES,2021-05-26
262,263,Univ.Prof. Rosalinde Möchlichen,lambertthanel@example.net,NL,2025-08-16
263,264,Ortrun Briemer,dippelheino@example.com,IT,2023-10-18
264,265,Albina Segebahn,bkraushaar@example.com,CH,2023-03-07
265,266,Rainer Lorch,qhaering@example.com,CH,2022-10-26
266,267,Dogan Jessel,elma66@example.org,GB,2021-09-09
267,268,Univ.Prof. Jane Bolnbach,soenke72@example.net,DE,2022-12-16
268,269,Isa Gotthard,fischerantonios@example.net,NL,2024-10-27
269,270,Selma Henck,zdoerschner@example.com,DE,2020-08-13
270,271,Elsa Börner,hesserosel@example.org,DE,2022-04-13
271,272,Ira Drubin,nsalz@example.com,ES,2021-10-22
272,273,Kerstin Atzler-Eigenwillig,kensyadeline@example.org,PL,2020-12-08
273,274,Herr Ilias Anders B.A.,franca81@example.org,FR,2020-10-27
274,275,Freia Röhricht,romanatroest@example.org,PL,2022-07-08
275,276,Univ.Prof. Knud Dietz,tomislav90@example.org,IT,2024-04-08
276,277,Rolf-Dieter Putz,davidklingelhoefer@example.net,CH,2020-05-18
277,278,Herr Hasso Baum B.Sc.,lili60@example.com,BE,2020-09-17
278,279,Antonina Binner,zdoehn@example.com,DE,2022-01-06
279,280,Ing. Dominic Fliegner B.Sc.,anne32@example.net,NL,2025-05-28
280,281,Prof. Isabell Patberg B.Sc.,rosenowmaria-luise@example.com,FR,2024-09-28
281,282,Tilmann Wernecke B.A.,selim63@example.org,FR,2020-01-12
282,283,Antje Käster,janepreiss@example.com,AT,2025-08-15
283,284,Nora Jacob,frankeheinz-willi@example.org,BE,2025-07-17
284,285,Knut Stey B.Eng.,camillaseip@example.net,CH,2024-09-04
285,286,Mariusz Gude,smuelichen@example.net,IT,2022-11-01
286,287,Jeannine Heser,imangold@example.com,IT,2025-10-03
287,288,Liliana Hamann,januszschmidt@example.net,ES,2023-09-01
288,289,Ioannis Heydrich,amans@example.org,AT,2023-12-29
289,290,Dipl.-Ing. Karl-Friedrich Heintze MBA.,patric66@example.com,PL,2023-01-14
290,291,Dusan Fiebig-Reising,drogge@example.net,FR,2024-06-08
291,292,Hendrik Drub-Gerlach,ghuebel@example.net,PL,2020-07-08
292,293,Prof. Wenke Lachmann,kpruschke@example.net,CH,2024-02-20
293,294,Walther Rosemann,joergbohnbach@example.net,ES,2024-09-14
294,295,Gottlieb Herrmann-Keudel,anatolisiering@example.org,PL,2021-03-26
295,296,Dr. Leonie Kensy,thorsten98@example.org,AT,2025-03-16
296,297,Arndt Langern,sjunck@example.org,AT,2020-01-06
297,298,Ing. Dorota Bolander,magnus30@example.com,CH,2021-07-05
298,299,Prof. Gunda Gierschner B.Sc.,jgnatz@example.org,CH,2020-12-19
299,300,Helen Christoph-Gnatz,oderwaldcosimo@example.org,CH,2023-12-21
300,301,Kata Holzapfel,xluebs@example.com,PL,2021-09-13
301,302,Claus Misicher,hartmannangelica@example.net,AT,2021-12-28
302,303,Fanny Mühle,klaus-juergenheintze@example.net,DE,2024-02-08
303,304,Therese Juncken B.Sc.,jacek16@example.org,PL,2025-05-04
304,305,Dipl.-Ing. Ricardo Dobes,valerijladeck@example.net,NL,2024-08-24
305,306,Traute Schulz,roemerharry@example.com,CH,2020-10-13
306,307,Dagobert Drub-Preiß,filippohettner@example.net,ES,2022-07-29

=== customers_clean: 0 duplicate rows (subset=all columns) ===

Empty DataFrame
Columns: [customer_id, full_name, email, country_code, registered_at]
Index: []

=== customers_raw: 33 fuzzy pairs (threshold=80, cols=['full_name', 'email']) ===

,score,idx_a,idx_b,full_name_a,email_a,full_name_b,email_b
0,100.0,25,300,Marieluise Schmidtke,tmargraf@example.org,Marieluise Schmidtke,tmargraf@example.org
1,100.0,372,464,Vittorio Beer,jovanjunk@example.net,Vittorio Beer,jovanjunk@example.net
2,100.0,43,296,Klaus Dieter Beckmann,lindaukrzysztof@example.com,Klaus Dieter Beckmann,lindaukrzysztof@example.com
3,100.0,61,495,Annedore Hesse,ifaust@example.net,Annedore Hesse,ifaust@example.net
4,100.0,96,261,Univ.Prof. Ivanka Fröhlich,brit28@example.net,Univ.Prof. Ivanka Fröhlich,brit28@example.net
5,100.0,91,529,Joachim Huhn,ldavids@example.net,Joachim Huhn,ldavids@example.net
6,100.0,75,454,Sieglinde Gutknecht MBA.,esiering@example.org,Sieglinde Gutknecht MBA.,esiering@example.org
7,100.0,69,135,Giorgio Rogge,anna-maria54@example.com,Giorgio Rogge,anna-maria54@example.com
8,100.0,64,143,Gerdi Striebitz-Kühnert,ngnatz@example.net,Gerdi Striebitz-Kühnert,ngnatz@example.net
9,100.0,93,136,Dr. Linda Hendriks,sigurd51@example.net,Dr. Linda Hendriks,sigurd51@example.net
10,100.0,289,340,Matthäus Bolander,antoniojaekel@example.com,Matthäus Bolander,antoniojaekel@example.com
11,100.0,299,323,Gretel Juncken,gustav66@example.org,Gretel Juncken,gustav66@example.org
12,100.0,238,279,Korinna Roskoth,miroslavkusch@example.com,Korinna Roskoth,miroslavkusch@example.com
13,100.0,200,468,Gundolf Staude,orhanschuster@example.net,Gundolf Staude,orhanschuster@example.net
14,100.0,231,288,Frau Heidelinde Hiller B.A.,cathleenbaehr@example.com,Frau Heidelinde Hiller B.A.,cathleenbaehr@example.com
15,100.0,159,404,Frau Gerhild Sölzer B.Sc.,evelin09@example.com,Frau Gerhild Sölzer B.Sc.,evelin09@example.com
16,100.0,147,515,Prof. Alois Börner,moritzpergande@example.com,Prof. Alois Börner,moritzpergande@example.com
17,100.0,302,435,Ing. Aysel Rörricht,desireeklapp@example.net,Ing. Aysel Rörricht,desireeklapp@example.net
18,100.0,394,516,Ing. Dominic Fliegner B.Sc.,anne32@example.net,Ing. Dominic Fliegner B.Sc.,anne32@example.net
19,100.0,265,406,Tomasz Rörricht,heide-marie69@example.org,Tomasz Rörricht,heide-marie69@example.org
20,96.4,87,421,Manja Wagner B.Sc.,rudolp.hbogdan@example.com,Manja Wagner B.Sc.,rudolphbogdan@example.com
21,96.0,341,388,Dipl.-Ing. Attila Gehringer B.A.,fritschmechtild@example.org,Dipl.-Ing. Attila Gehringer B.A.,fritschmechtild@example.org
22,95.7,57,449,Brigitta Weimer B.A.,ryszardmitschke@example.com,Brigtita Weimer B.A.,ryszardmitschke@example.com
23,95.6,19,339,Ilias Roskot-hKöster,valentinenette@example.com,Ilias Roskoth-Köster,valentinenette@example.com
24,95.6,130,214,Prof. Pierre Stadelmann B.A.,wolfhardhoefig@example.org,Prof. Pierre Stadelmann B.A.,wolfhardhoefig@example.org
25,95.1,34,504,Till Schacht MBA.,mgierschner@example.com,Till Schacht MBA.,mgierschner@example.com
26,95.0,392,539,Dr. Marietta Matthäi B.A.,hiltraud62@example.org,Dr. Marietta Matthäi B.A.,hiltraud62@example.org
27,94.6,59,518,Helma Grein Groth,dhande@example.net,Helma X. Grein Groth,dha.nde@example.net
28,94.2,172,364,Hanne van der Dussen,patrick94@example.com,Hanne van der Dussen,patrick94@example.com
29,92.8,73,333,Antonina Binner,zdoehn@example.com,Antonina X. Binner,zdoehn@example.com
30,90.2,55,346,cosima hiller,evangelos37@example.com,Cosima Hiller,evangelos37@example.com
31,82.1,32,482,Fabian Staude-Krein,wwilms@example.org,Fabian Staude-Krein,WWILMS@example.org
32,80.2,216,335,Leopoldine Köster,oreuter@example.net,Leopoldine Köster,OREUTER@example.net

In [16]:
# Products

show_all(products_raw.sort_values("product_id"), "products_raw")     #sorted
show_all(products_clean.sort_values("product_id"), "products_clean") 
#show_all(products, "products")                               #unsorted

# Duplicates

inspect_duplicates(products_raw, name="products_raw")
#inspect_duplicates(products_clean, subset=["product_id"], name="products_clean")

=== products_raw: 100 rows ===

,product_id,name,category,price_eur,in_stock
0,1,Multi-layered systemic attitude,Sports,30.78 EUR,no
1,2,Synergistic encompassing array,Electronics,336.58,yes
2,3,Expanded zero-defect parallelism,Sports,"105,09",1
3,4,Organized background migration,Home,436.74 EUR,1
4,5,Devolved discrete ability,Sports,"123,92",yes
5,6,Versatile actuating circuit,Electronics,436.44,1
6,7,Focused hybrid archive,Toys,59.22,1
7,8,Decentralized homogeneous superstructure,Books,301.34,yes
8,9,Cloned heuristic portal,Clothing,475.06 EUR,true
9,10,Pre-emptive national hardware,Electronics,358.81 EUR,yes
10,11,Versatile background core,Toys,396.15 EUR,0
11,12,Exclusive human-resource hub,Toys,"144,07",yes
12,13,Assimilated context-sensitive analyzer,Home,€346.20,1
13,14,Implemented content-based firmware,Home,284.51 EUR,1
14,15,Phased intermediate matrix,Sports,387.71,no
15,16,Realigned object-oriented architecture,Sports,474.07 EUR,1
16,17,Proactive value-added Internet solution,Sports,249.62 EUR,1
17,18,Reverse-engineered composite methodology,Sports,335.31,false
18,19,Synergistic solution-oriented synergy,Home,"426,63",0
19,20,Synchronized upward-trending intranet,Books,"186,39",1
20,21,Extended heuristic contingency,Home,282.15,true
21,22,Future-proofed real-time framework,Toys,€123.69,1
22,23,Function-based full-range emulation,Toys,€250.13,true
23,24,Programmable optimizing workforce,Sports,148.28,0
24,25,Multi-tiered zero-defect infrastructure,Books,€56.73,1
25,26,Switchable composite array,Electronics,174.27 EUR,yes
26,27,Future-proofed optimizing adapter,Books,"160,47",1
27,28,Horizontal encompassing definition,Electronics,€309.36,false
28,29,Monitored modular encryption,Clothing,€480.78,1
29,30,Secured user-facing moderator,Books,"262,20",1
30,31,Streamlined system-worthy customer loyalty,Sports,139.90 EUR,0
31,32,Exclusive foreground capacity,Toys,408.54,false
32,33,Universal user-facing task-force,Sports,337.46,1
33,34,Compatible interactive help-desk,Home,351.41,true
34,35,Quality-focused directional frame,Electronics,145.28 EUR,yes
35,36,Advanced composite customer loyalty,Electronics,"143,90",true
36,37,Fully-configurable incremental project,Books,225.23,false
37,38,Down-sized secondary service-desk,Electronics,€195.23,0
38,39,Seamless full-range customer loyalty,Electronics,387.46,true
39,40,De-engineered executive capacity,Sports,€21.86,no
40,41,Grass-roots needs-based protocol,Toys,148.99,1
41,42,Reactive disintermediate hierarchy,Electronics,€156.55,1
42,43,Horizontal stable synergy,Clothing,€70.49,true
43,44,Re-contextualized transitional customer loyalty,Toys,€473.86,yes
44,45,Mandatory foreground knowledgebase,Books,427.06,1
45,46,Open-source needs-based Internet solution,Sports,"244,23",yes
46,47,Cross-platform user-facing focus group,Sports,264.87 EUR,true
47,48,Compatible homogeneous implementation,Sports,€481.73,0
48,49,Extended secondary strategy,Toys,191.31,true
49,50,Team-oriented foreground project,Toys,168.94 EUR,1
50,51,Triple-buffered composite benchmark,Toys,"361,77",1
51,52,Multi-tiered non-volatile success,Electronics,€397.15,true
52,53,Synergistic bi-directional Graphical User Inte...,Clothing,296.88,false
53,54,Fully-configurable background standardization,Home,"362,56",no
54,55,Multi-lateral empowering firmware,Electronics,€160.26,0
55,56,Extended mobile conglomeration,Electronics,349.97 EUR,true
56,57,Multi-layered intangible middleware,Sports,407.12,yes
57,58,Re-contextualized client-driven intranet,Clothing,€257.77,true
58,59,Digitized actuating focus group,Toys,€469.31,yes
59,60,Focused radical software,Toys,€446.37,true
60,61,User-friendly executive orchestration,Sports,"491,10",1
61,62,Self-enabling clear-thinking customer loyalty,Books,325.02 EUR,yes
62,63,Seamless 24hour database,Electronics,€304.56,false
63,64,Distributed disintermediate extranet,Home,228.28 EUR,true
64,65,Compatible secondary open architecture,Toys,286.49 EUR,true
65,66,Realigned intermediate focus group,Electronics,118.41 EUR,1
66,67,Universal intermediate analyzer,Electronics,€286.94,1
67,68,Organized logistical productivity,Clothing,222.72,yes
68,69,Reverse-engineered homogeneous success,Books,159.00 EUR,yes
69,70,Advanced system-worthy success,Toys,134.20,yes
70,71,Fundamental logistical attitude,Books,268.41 EUR,1
71,72,Fundamental dedicated capacity,Books,€263.64,1
72,73,Ergonomic bandwidth-monitored groupware,Electronics,84.46,1
73,74,Re-engineered modular ability,Clothing,31.28,1
74,75,Multi-layered content-based challenge,Toys,152.31 EUR,yes
75,76,Progressive fault-tolerant complexity,Toys,"269,90",true
76,77,Total client-server conglomeration,Books,"208,09",no
77,78,Compatible transitional core,Books,€319.80,1
78,79,Team-oriented bottom-line extranet,Sports,"377,95",yes
79,80,Intuitive contextually-based monitoring,Clothing,450.73,1
80,81,Mandatory fresh-thinking emulation,Clothing,"246,31",true
81,82,Customizable fault-tolerant framework,Electronics,226.04 EUR,1
82,83,Visionary context-sensitive adapter,Home,19.76 EUR,no
83,84,Customizable clear-thinking toolset,Clothing,287.39 EUR,true
84,85,Sharable solution-oriented interface,Clothing,286.49 EUR,yes
85,86,Exclusive encompassing benchmark,Books,196.55 EUR,true
86,87,Multi-lateral zero tolerance hardware,Sports,132.73,0
87,88,Managed asymmetric hierarchy,Clothing,"371,42",yes
88,89,Intuitive high-level analyzer,Electronics,72.65 EUR,1
89,90,Ergonomic cohesive success,Clothing,"298,42",no
90,91,Self-enabling impactful firmware,Toys,€47.16,yes
91,92,Business-focused bifurcated database,Sports,"314,98",no
92,93,Exclusive clear-thinking firmware,Electronics,€376.55,0
93,94,Proactive 24/7 encoding,Toys,159.53 EUR,yes
94,95,Devolved motivating Graphical User Interface,Books,66.74 EUR,0
95,96,Focused next generation Graphical User Interface,Sports,230.63 EUR,true
96,97,Ergonomic multi-state product,Electronics,287.61,1
97,98,Intuitive asymmetric projection,Books,€134.52,true
98,99,Down-sized neutral workforce,Sports,323.65 EUR,1
99,100,Self-enabling multimedia open system,Sports,414.40 EUR,0

=== products_clean: 100 rows ===

,product_id,name,category,price_eur,in_stock
0,1,Multi-layered systemic attitude,Sports,30.78,False
1,2,Synergistic encompassing array,Electronics,336.58,True
2,3,Expanded zero-defect parallelism,Sports,105.09,True
3,4,Organized background migration,Home,436.74,True
4,5,Devolved discrete ability,Sports,123.92,True
5,6,Versatile actuating circuit,Electronics,436.44,True
6,7,Focused hybrid archive,Toys,59.22,True
7,8,Decentralized homogeneous superstructure,Books,301.34,True
8,9,Cloned heuristic portal,Clothing,475.06,True
9,10,Pre-emptive national hardware,Electronics,358.81,True
10,11,Versatile background core,Toys,396.15,False
11,12,Exclusive human-resource hub,Toys,144.07,True
12,13,Assimilated context-sensitive analyzer,Home,346.20,True
13,14,Implemented content-based firmware,Home,284.51,True
14,15,Phased intermediate matrix,Sports,387.71,False
15,16,Realigned object-oriented architecture,Sports,474.07,True
16,17,Proactive value-added Internet solution,Sports,249.62,True
17,18,Reverse-engineered composite methodology,Sports,335.31,False
18,19,Synergistic solution-oriented synergy,Home,426.63,False
19,20,Synchronized upward-trending intranet,Books,186.39,True
20,21,Extended heuristic contingency,Home,282.15,True
21,22,Future-proofed real-time framework,Toys,123.69,True
22,23,Function-based full-range emulation,Toys,250.13,True
23,24,Programmable optimizing workforce,Sports,148.28,False
24,25,Multi-tiered zero-defect infrastructure,Books,56.73,True
25,26,Switchable composite array,Electronics,174.27,True
26,27,Future-proofed optimizing adapter,Books,160.47,True
27,28,Horizontal encompassing definition,Electronics,309.36,False
28,29,Monitored modular encryption,Clothing,480.78,True
29,30,Secured user-facing moderator,Books,262.20,True
30,31,Streamlined system-worthy customer loyalty,Sports,139.90,False
31,32,Exclusive foreground capacity,Toys,408.54,False
32,33,Universal user-facing task-force,Sports,337.46,True
33,34,Compatible interactive help-desk,Home,351.41,True
34,35,Quality-focused directional frame,Electronics,145.28,True
35,36,Advanced composite customer loyalty,Electronics,143.90,True
36,37,Fully-configurable incremental project,Books,225.23,False
37,38,Down-sized secondary service-desk,Electronics,195.23,False
38,39,Seamless full-range customer loyalty,Electronics,387.46,True
39,40,De-engineered executive capacity,Sports,21.86,False
40,41,Grass-roots needs-based protocol,Toys,148.99,True
41,42,Reactive disintermediate hierarchy,Electronics,156.55,True
42,43,Horizontal stable synergy,Clothing,70.49,True
43,44,Re-contextualized transitional customer loyalty,Toys,473.86,True
44,45,Mandatory foreground knowledgebase,Books,427.06,True
45,46,Open-source needs-based Internet solution,Sports,244.23,True
46,47,Cross-platform user-facing focus group,Sports,264.87,True
47,48,Compatible homogeneous implementation,Sports,481.73,False
48,49,Extended secondary strategy,Toys,191.31,True
49,50,Team-oriented foreground project,Toys,168.94,True
50,51,Triple-buffered composite benchmark,Toys,361.77,True
51,52,Multi-tiered non-volatile success,Electronics,397.15,True
52,53,Synergistic bi-directional Graphical User Inte...,Clothing,296.88,False
53,54,Fully-configurable background standardization,Home,362.56,False
54,55,Multi-lateral empowering firmware,Electronics,160.26,False
55,56,Extended mobile conglomeration,Electronics,349.97,True
56,57,Multi-layered intangible middleware,Sports,407.12,True
57,58,Re-contextualized client-driven intranet,Clothing,257.77,True
58,59,Digitized actuating focus group,Toys,469.31,True
59,60,Focused radical software,Toys,446.37,True
60,61,User-friendly executive orchestration,Sports,491.10,True
61,62,Self-enabling clear-thinking customer loyalty,Books,325.02,True
62,63,Seamless 24hour database,Electronics,304.56,False
63,64,Distributed disintermediate extranet,Home,228.28,True
64,65,Compatible secondary open architecture,Toys,286.49,True
65,66,Realigned intermediate focus group,Electronics,118.41,True
66,67,Universal intermediate analyzer,Electronics,286.94,True
67,68,Organized logistical productivity,Clothing,222.72,True
68,69,Reverse-engineered homogeneous success,Books,159.00,True
69,70,Advanced system-worthy success,Toys,134.20,True
70,71,Fundamental logistical attitude,Books,268.41,True
71,72,Fundamental dedicated capacity,Books,263.64,True
72,73,Ergonomic bandwidth-monitored groupware,Electronics,84.46,True
73,74,Re-engineered modular ability,Clothing,31.28,True
74,75,Multi-layered content-based challenge,Toys,152.31,True
75,76,Progressive fault-tolerant complexity,Toys,269.90,True
76,77,Total client-server conglomeration,Books,208.09,False
77,78,Compatible transitional core,Books,319.80,True
78,79,Team-oriented bottom-line extranet,Sports,377.95,True
79,80,Intuitive contextually-based monitoring,Clothing,450.73,True
80,81,Mandatory fresh-thinking emulation,Clothing,246.31,True
81,82,Customizable fault-tolerant framework,Electronics,226.04,True
82,83,Visionary context-sensitive adapter,Home,19.76,False
83,84,Customizable clear-thinking toolset,Clothing,287.39,True
84,85,Sharable solution-oriented interface,Clothing,286.49,True
85,86,Exclusive encompassing benchmark,Books,196.55,True
86,87,Multi-lateral zero tolerance hardware,Sports,132.73,False
87,88,Managed asymmetric hierarchy,Clothing,371.42,True
88,89,Intuitive high-level analyzer,Electronics,72.65,True
89,90,Ergonomic cohesive success,Clothing,298.42,False
90,91,Self-enabling impactful firmware,Toys,47.16,True
91,92,Business-focused bifurcated database,Sports,314.98,False
92,93,Exclusive clear-thinking firmware,Electronics,376.55,False
93,94,Proactive 24/7 encoding,Toys,159.53,True
94,95,Devolved motivating Graphical User Interface,Books,66.74,False
95,96,Focused next generation Graphical User Interface,Sports,230.63,True
96,97,Ergonomic multi-state product,Electronics,287.61,True
97,98,Intuitive asymmetric projection,Books,134.52,True
98,99,Down-sized neutral workforce,Sports,323.65,True
99,100,Self-enabling multimedia open system,Sports,414.40,False

=== products_raw: 0 duplicate rows (subset=all columns) ===

Empty DataFrame
Columns: [product_id, name, category, price_eur, in_stock]
Index: []

In [17]:
# Orders

show_all(orders.sort_values("order_id"), "orders")          #sorted
#show_all(orders, "orders")                                 #unsorted

# Duplicates

inspect_duplicates(orders, name="orders")
#inspect_duplicates(orders, subset=["order_id"], name="orders")

NameError: name 'orders' is not defined